apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend3
  template:
    metadata:
      labels:
        app: backend3
    spec:
      containers:
      - name: backend3
        image: 650089658128.dkr.ecr.ap-south-1.amazonaws.com/backend3:1  # Replaced by sed in pipeline
        ports:
        - containerPort: 3000
        resources:
          requests:
            cpu: "250m"
            memory: "512Mi"
          limits:
            cpu: "500m"
            memory: "1Gi"
        
---
apiVersion: v1
kind: Service
metadata:
  name: backend3-service
spec:
  selector:
    app: backend3
  ports:
    - protocol: TCP
      port: 80          
      targetPort: 3000  
 
